---
title: "Lesson 2: Getting Started: From AI to ML "
output: html_notebook
---

## AI Problems 

5 Conundrums

1. Intelligent agents have limited resource
2. Computation is local, but problems have global constraints
3. Logic is deductive, but many AI problems are abductive/inductive
4. The world is dynamic, but knowledge is limited. AI begins with what
it already knows, so how can it address new problems?
5. How can AI explain or justify decisions? 

AI Problems

1. Knowledge often arrives incrementally
2. Problems exhibit recurring patterns
3. Problems have multiple levels of granularity
4. Problems are computationally intractable
5. World is dynamic, but knowledge is static
6. World is opened-ended. 

Another View:

AI = What to do when you don't know what to do? (AI as 
uncertainty management)

Reasons: sensor limits, adversaries, stochastic environments,
laziness, ignorance

## Watson and Knowledge Based AI

- Reasoning: making decisions, understanding through learning/memory
- Learning: learn from right/wrong answers to motivate future decisions
- Memory: remember knowledge from learning, provide knowledge to reasoning

## Four Schools of AI

thinking vs. acting and optimal vs. human-like agents. 
machine learning: optimal thinking
airplane autopilot: optimal acting
improvisational robots: human acting
semantic web: thinking like humans

## Bayes Rule Intro

$P (A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}$

POSTERIOR = LIKELIHOOD * PRIOR / MARGINAL LIKELIHOOD

We know about B, but care about variable A. 
The diagnostic (posterior) reasoning from evidence to casues 
uses Bayes rule into causal rule, given hyopthethically we
knew the cause, what is the probability of the evidence
observed, multiplied by the prior of the cause in the
first place, divded by the probably of the evidence. 

$P(B) = \sum_{a} P(B|A=a)P(A=a)$

(A) = Cancer
(B) = Test

A is observable, but B is not. 

Bayes Network is composted of (A) --> (B)

We know: P(A) - having cancer, and P(B|A) 
Diagnostic reasoning: P(A|B)

Three parameters required: P(A) 

## Definitions

### Taxonomy

- What? parameters, strucutre, hidden concepts
- What form? supervied, unsupervied, reinforcement
- What for? prediction, siganostics, summarization
- How? passive, active, online, offline
- Outputs? classification, regression
- Details? Generative, descriminative


### Linear Regression

Loss function: residual error after fitting linear function

$\sum_j(y_j - w_1x_j-W_o)^2$

w* = argmin(?) Loss w


